# Generated by Django 2.0 on 2020-02-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataprocessing', '0010_auto_20200216_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomesOfWorkProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterylevel', models.CharField(choices=[('1', 'low'), ('2', 'average'), ('3', 'high')], default=1, max_length=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprocessing.Items')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisitesOfWorkProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterylevel', models.CharField(choices=[('1', 'low'), ('2', 'average'), ('3', 'high')], default=1, max_length=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprocessing.Items')),
            ],
        ),
        migrations.CreateModel(
            name='WorkProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('hoursFirstSemester', models.IntegerField(null=True)),
                ('hoursSecondSemester', models.IntegerField(null=True)),
                ('outcomes', models.ManyToManyField(related_name='WorkProgramOutcomes', through='workprogramsapp.OutcomesOfWorkProgram', to='dataprocessing.Items')),
                ('prerequisites', models.ManyToManyField(related_name='WorkProgramPrerequisites', through='workprogramsapp.PrerequisitesOfWorkProgram', to='dataprocessing.Items')),
            ],
        ),
        migrations.AddField(
            model_name='prerequisitesofworkprogram',
            name='workprogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.WorkProgram'),
        ),
        migrations.AddField(
            model_name='outcomesofworkprogram',
            name='workprogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.WorkProgram'),
        ),
    ]
