# Generated by Django 2.0.5 on 2020-02-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcomesofworkprogram',
            name='item',
        ),
        migrations.RemoveField(
            model_name='outcomesofworkprogram',
            name='workprogram',
        ),
        migrations.RemoveField(
            model_name='prerequisitesofworkprogram',
            name='item',
        ),
        migrations.RemoveField(
            model_name='prerequisitesofworkprogram',
            name='workprogram',
        ),
        migrations.AlterField(
            model_name='workprogram',
            name='outcomes',
            field=models.ManyToManyField(related_name='WorkProgramOutcomes', to='dataprocessing.Items'),
        ),
        migrations.AlterField(
            model_name='workprogram',
            name='prerequisites',
            field=models.ManyToManyField(related_name='WorkProgramPrerequisites', to='dataprocessing.Items'),
        ),
        migrations.DeleteModel(
            name='OutcomesOfWorkProgram',
        ),
        migrations.DeleteModel(
            name='PrerequisitesOfWorkProgram',
        ),
    ]
