# Generated by Django 2.0.5 on 2019-12-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('0', 'неопределенное'), ('1', 'включает в себя'), ('2', 'является пререквезитом'), ('3', 'тождество'), ('4', 'являются частями одного раздела'), ('5', 'отсутствует')], default='0', max_length=10)),
                ('item1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='dataprocessing.Items')),
                ('item2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='dataprocessing.Items')),
            ],
        ),
    ]
