# Generated by Django 2.0.5 on 2019-12-15 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0003_auto_20191201_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='domain',
            field=models.ForeignKey(blank=True, help_text='Укажите область', on_delete=django.db.models.deletion.CASCADE, to='dataprocessing.Domain', verbose_name='Область знаний'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation',
            field=models.CharField(choices=[('0', 'неопределенное'), ('1', 'включает в себя'), ('2', 'является пререквизитом'), ('3', 'тождество'), ('4', 'являются частями одного раздела'), ('5', 'отсутствует')], default='0', max_length=10),
        ),
    ]
