# Generated by Django 2.0.5 on 2019-12-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0004_auto_20191215_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='domain',
            field=models.ForeignKey(blank=True, help_text='Укажите область', null=True, on_delete=django.db.models.deletion.CASCADE, to='dataprocessing.Domain', verbose_name='Область знаний'),
        ),
    ]
