# Generated by Django 2.0.5 on 2019-12-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0007_auto_20191218_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='item1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='dataprocessing.Items', verbose_name='Элемент РПД'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='item2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='dataprocessing.Items', verbose_name='Элемент РПД'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation',
            field=models.CharField(choices=[('0', 'неопределенное'), ('1', 'включает в себя'), ('2', 'относится к'), ('3', 'является пререквизитом'), ('4', 'тождество'), ('5', 'являются частями одного раздела'), ('6', 'отсутствует')], default='1', max_length=10, verbose_name='Связь'),
        ),
    ]
