# Generated by Django 2.0 on 2020-02-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0009_auto_20191229_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='item',
        ),
        migrations.RemoveField(
            model_name='data',
            name='user',
        ),
        migrations.AlterField(
            model_name='items',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation',
            field=models.CharField(choices=[('0', 'неопределенное'), ('1', 'включает в себя'), ('2', 'относится к'), ('3', 'является пререквизитом для'), ('4', 'имеет пререквизит'), ('5', 'тождество'), ('6', 'являются частями одного раздела'), ('7', 'отсутствует')], default='1', max_length=10, verbose_name='Связь'),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
